In [1]:
import pandas as pd
import numpy as np

In [2]:
train_df = pd.read_csv('./out/cleaned_train.csv')
train_df

         DAY_OF_WEEK   TIME  BUS_ID  BUSROUTE_ID  BUSSTOP_ID  TIMESTAMP_DIFF
0                  0   5305       0            3          17           117.0
1                  0   5422       0            3          10           123.0
2                  0   5545       0            3           8           121.0
3                  0   5666       0            3           5           136.0
4                  0   5802       0            3           3           174.0
...              ...    ...     ...          ...         ...             ...
3113890            4  56850    1076            8         109            74.0
3113891            4  56924    1076            8         117           123.0
3113892            4  57047    1076            8         119            91.0
3113893            4  57138    1076            8         121            82.0
3113894            4  57220    1076            8         624            49.0

[3113895 rows x 6 columns]

In [3]:
import random
# 5000-н урттай дарааллаас хамгийн ихдээ 50 урттай дэд цонхнууд үүсгэх туршилт
# мөн тэндээс санамсаргүй sample сонгох
def generate_n_sample_indexes(seq_len=5000, window_len=50, sample_size=10):
    l = [n for n in range(1, seq_len)]
    start_idx = 0

    total_sample_indexes = []
    for i in range(start_idx, seq_len-window_len+1):
        for j in range(i+1, i+window_len+1):
            total_sample_indexes.append((i,j))

    return random.choices(total_sample_indexes, k=sample_size)

print(generate_n_sample_indexes())

[(779, 820), (4282, 4295), (1868, 1883), (4853, 4874), (3722, 3756), (1860, 1896), (4158, 4199), (3983, 3994), (859, 899), (2960, 2968)]

In [4]:
total_generated_samples = 500000
print("total needed samples", total_generated_samples)
print("route count", len(train_df['BUSROUTE_ID'].unique()))
samples_per_route       = int(total_generated_samples/len(train_df['BUSROUTE_ID'].unique()))
print("sample needed per route", samples_per_route)
sample_buses_per_route  = 20
samples_per_bus         = int(samples_per_route/sample_buses_per_route)
print("sample needed per bus", samples_per_bus)
bus_history_treshold    = 500

total needed samples 500000
route count 102
sample needed per route 4901
sample needed per bus 245

In [5]:
dataset = []

# Бүх чиглэлийг хамрах
for idx, route_id in enumerate(train_df['BUSROUTE_ID'].unique()):
    print("proccessing at route", route_id)
    # энэ чиглэлээс санамсаргүй автобус сонгох гэхдээ тодорхой тооноос дээш бичлэгтэй
    filtered_df = train_df[(train_df['BUSROUTE_ID']==route_id)].groupby("BUS_ID").filter(lambda x: len(x)>bus_history_treshold)
    # шүүлт хийгдсэн бичлэгнээс санамсаргүй хэдэн автобус сонгох
    filtered_buses = filtered_df['BUS_ID'].unique()
    if len(filtered_buses)==0:
        continue
    if len(filtered_buses)<sample_buses_per_route:
        bus_sample_count = len(filtered_buses)
    else:
        bus_sample_count = sample_buses_per_route
    selected_buses = random.choices(filtered_df['BUS_ID'].unique(), k=sample_buses_per_route)
    selected_buses = np.unique(selected_buses).tolist()
    
    # сонгогдсон автобуснуудаас тодорхой тооны явсан түүх үүсгэх
    for bus_id in selected_buses:
        bus_history     = filtered_df[filtered_df['BUS_ID']==bus_id]
        bus_history_len = len(bus_history)
        sample_indexes  = generate_n_sample_indexes(seq_len=bus_history_len, window_len=50, sample_size=samples_per_bus)
        for idx_pair in sample_indexes:
            # автобус бүр хамгийн оптимал утгаар хөдлөнө гэж үзээд BUS_ID-г хаслаа
            # DAY_OF_WEEK, TIME, BUSROUTE_ID, BUSSTOP_ID, TIMESTAMP_DIFF
            dataset.append(bus_history[['DAY_OF_WEEK', 'TIME', 'BUSROUTE_ID', 'BUSSTOP_ID', 'TIMESTAMP_DIFF']].iloc[idx_pair[0]:idx_pair[1]].values.tolist())
    #break

print("done, total generated", len(dataset))

proccessing at route 3
proccessing at route 166
proccessing at route 142
proccessing at route 214
proccessing at route 61
proccessing at route 16
proccessing at route 100
proccessing at route 96
proccessing at route 127
proccessing at route 150
proccessing at route 5
proccessing at route 156
proccessing at route 34
proccessing at route 180
proccessing at route 196
proccessing at route 253
proccessing at route 49
proccessing at route 255
proccessing at route 50
proccessing at route 223
proccessing at route 12
proccessing at route 104
proccessing at route 92
proccessing at route 198
proccessing at route 121
proccessing at route 108
proccessing at route 203
proccessing at route 175
proccessing at route 59
proccessing at route 147
proccessing at route 236
proccessing at route 58
proccessing at route 8
proccessing at route 70
proccessing at route 265
proccessing at route 170
proccessing at route 74
proccessing at route 173
proccessing at route 251
proccessing at route 99
proccessing at route 89
proccessing at route 219
proccessing at route 240
proccessing at route 69
proccessing at route 66
proccessing at route 13
proccessing at route 137
proccessing at route 168
proccessing at route 39
proccessing at route 80
proccessing at route 232
proccessing at route 220
proccessing at route 268
proccessing at route 270
proccessing at route 260
proccessing at route 45
proccessing at route 193
proccessing at route 271
proccessing at route 135
proccessing at route 140
proccessing at route 55
proccessing at route 206
proccessing at route 119
proccessing at route 115
proccessing at route 190
proccessing at route 25
proccessing at route 152
proccessing at route 162
proccessing at route 242
proccessing at route 123
proccessing at route 65
proccessing at route 221
proccessing at route 259
proccessing at route 46
proccessing at route 188
proccessing at route 41
proccessing at route 179
proccessing at route 144
proccessing at route 107
proccessing at route 117
proccessing at route 83
proccessing at route 164
proccessing at route 200
proccessing at route 133
proccessing at route 266
proccessing at route 73
proccessing at route 60
proccessing at route 207
proccessing at route 30
proccessing at route 201
proccessing at route 224
proccessing at route 217
proccessing at route 95
proccessing at route 225
proccessing at route 114
proccessing at route 90
proccessing at route 160
proccessing at route 77
proccessing at route 130
proccessing at route 246
proccessing at route 212
proccessing at route 209
done, total generated 249165

In [6]:
np.save("./seq_dataset.npy", np.array(dataset))